using System;
/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Fri May 15 2020 14:01:25 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.domain.Parametres.Messages.Commands
{
    public class DeleteParametre: ParametreBaseCommand
    {
        
        public override Guid Id { get; set; }
        public DeleteParametre(Guid id) : base()
        {
            this.Id = id;
        }
        

    }
}