using System;
using MicroS_Common.Messages;
/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Fri May 15 2020 14:01:25 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.domain.Parametres.Messages.Commands
{
    [MessageNamespace("parametres")]
    public abstract class ParametreBaseCommand : BaseCommand
    {

        public ParametreBaseCommand() : base()
        {
        }
    }
}
