version: "3.5"

services:
  mongo:
    image: mongo:4
    container_name: wecotation-mongo
    ports:
      - 27017:27017
    networks:
      - micros
    # network_mode: host
    volumes:
      - mongo:/data/db/mongo
    depends_on: 
      - portainer
  mongo-client:
    image: mongoclient/mongoclient
    container_name: wecotation-mongo-client
    depends_on: 
      - mongo
    ports:
      - 27018:3000
  rabbitmq:
    image: rabbitmq:3-management
    container_name: wecotation-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - micros
    # network_mode: host
    volumes: 
      - rabbitmq:/var/lib/rabbitmq
    depends_on: 
      - portainer

  redis:
    image: redis
    container_name: wecotation-redis
    ports:
      - 6379:6379
    networks:
      - micros
    # network_mode: host
    volumes: 
      - redis:/data
    depends_on: 
      - portainer
      
  portainer:
    image: portainer/portainer
    container_name: wecotation-portainer
    ports:
      - "9000:9000"
      - "9001:8000"
    volumes:
      - portainer_data:/portainer_data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - micros
  rebrow:
    image: marian/rebrow
    container_name: wecotation-rebrow
    ports:
      - "9002:5001"
    networks:
      - micros
    links:
      - redis
  
networks:
  micros:
    name: wecotation-micros-network

volumes:
  mongo:
    driver: local
  rabbitmq:
    driver: local
  redis:
    driver: local
  portainer_data:
    driver: local