using System;
using System.Collections.Generic;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Wed May 13 2020 12:07:33 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.domain.Operations.Dto
{
    public partial class OperationDto
    {

        #region private variables
        
        #endregion

        #region public properties
        
        
        public Guid Code  {get;set;}
        
        public int Ordre  {get;set;}
        
        public float Nombre  {get;set;}
        
        public int TxPrep  {get;set;}
        
        public int TxOpe  {get;set;}
        
        public float TpPrep  {get;set;}
        
        public float TpOpe  {get;set;}
        
        public float BaseOpe  {get;set;}
        
        public string Commentaire  {get;set;}
        
        
        #endregion


    }
}
