using AutoMapper;
using WeCotation.domain.Articles.Domain;
using WeCotation.domain.Articles.Dto;

using WeCotation.domain.Articles.Messages.Commands;
using WeCotation.domain.Articles.Messages.Events;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Wed May 13 2020 11:51:54 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.domain.Articles.Mapping
{
    public class ArticleProfile:Profile
    {
        public ArticleProfile()
        {
            this.AllowNullCollections = false;
            this.AllowNullDestinationValues = false;
            CreateMap<Article, ArticleDto>().ReverseMap().ForAllMembers(opts => { opts.Condition((src, dest, srcMember) => srcMember != null); });//.ConstructUsing(e => new ArticleDto() { Id = e.Id,Code = e.Code,Designation = e.Designation,Indice = e.Indice,Plan = e.Plan,Prix = e.Prix,Densite = e.Densite,TxPrep = e.TxPrep,TxOpe = e.TxOpe,TpPrep = e.TpPrep,TpOpe = e.TpOpe,TpBase = e.TpBase,Type = e.Type,Tarif = e.Tarif,Nomenclature = e.Nomenclature,Operation = e.Operation  });
            
            CreateMap<CreateArticle, Article>();//.ConstructUsing(e => new Article(e.Id,e.Code,e.Designation,e.Indice,e.Plan,e.Prix,e.Densite,e.TxPrep,e.TxOpe,e.TpPrep,e.TpOpe,e.TpBase,e.Type,e.Tarif,e.Nomenclature,e.Operation));
            CreateMap<CreateArticle, ArticleCreated>();//.ConstructUsing(e => new ArticleCreated(e.Id,e.Code,e.Designation,e.Indice,e.Plan,e.Prix,e.Densite,e.TxPrep,e.TxOpe,e.TpPrep,e.TpOpe,e.TpBase,e.Type,e.Tarif,e.Nomenclature,e.Operation));
            CreateMap<UpdateArticle, ArticleUpdated>();//.ConstructUsing(e => new ArticleUpdated(e.Id,e.Code,e.Designation,e.Indice,e.Plan,e.Prix,e.Densite,e.TxPrep,e.TxOpe,e.TpPrep,e.TpOpe,e.TpBase,e.Type,e.Tarif,e.Nomenclature,e.Operation));
            CreateMap<DeleteArticle, ArticleDeleted>();//.ConstructUsing(e => new ArticleDeleted(e.Id));            
            
        }
    }
}
