using AutoMapper;
using WeCotation.domain.Matieres.Domain;
using WeCotation.domain.Matieres.Dto;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun May 10 2020 17:30:35 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.domain.Matieres.Mapping
{
    public class MatiereProfile:Profile
    {
        public MatiereProfile()
        {
            CreateMap<Matiere, MatiereDto>().ConstructUsing(e => new MatiereDto() {Designation = e.Designation,PrixKg = e.PrixKg  });
            
        }
    }
}
