using System;
using System.Collections.Generic;


/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Fri May 15 2020 14:01:25 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.domain.Parametres.Messages.Events
{
    public class ParametreCreated : ParametreBaseEvent
    {
        public Guid Id { get; }

        public string  Code{get;}
        public string  Nom{get;}
        public string  Type{get;}
        public string  Aide{get;}
        
        
        public ParametreCreated(Guid id,
        string code,string nom,string type,string aide
        )
        {
            Id = id;
            Code = code ;
            Nom = nom ;
            Type = type ;
            Aide = aide ;
            
            
        }
    }
}
