using System;
/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Fri May 15 2020 14:01:25 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.domain.Parametres.Messages.Events
{
    public class UpdateParametreRejected : ParametreBaseRejectedEvent
    {
        public UpdateParametreRejected(Guid id, string reason, string code) : base(id, reason, code)
        {
        }
    }
}
