using AutoMapper;
using WeCotation.domain.TypeMatieres.Domain;
using WeCotation.domain.TypeMatieres.Dto;

using WeCotation.domain.TypeMatieres.Messages.Commands;
using WeCotation.domain.TypeMatieres.Messages.Events;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun May 10 2020 20:32:31 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.domain.TypeMatieres.Mapping
{
    public class TypeMatiereProfile:Profile
    {
        public TypeMatiereProfile()
        {
            CreateMap<TypeMatiere, TypeMatiereDto>();//.ConstructUsing(e => new TypeMatiereDto() { Id = e.Id,Nom = e.Nom,Densite = e.Densite,Matiere = e.Matiere  });
            
            CreateMap<CreateTypeMatiere, TypeMatiere>();//.ConstructUsing(e => new TypeMatiere(e.Id,e.Nom,e.Densite,e.Matiere));
            CreateMap<CreateTypeMatiere, TypeMatiereCreated>();//.ConstructUsing(e => new TypeMatiereCreated(e.Id,e.Nom,e.Densite,e.Matiere));
            CreateMap<UpdateTypeMatiere, TypeMatiereUpdated>();//.ConstructUsing(e => new TypeMatiereUpdated(e.Id,e.Nom,e.Densite,e.Matiere));
            CreateMap<DeleteTypeMatiere, TypeMatiereDeleted>();//.ConstructUsing(e => new TypeMatiereDeleted(e.Id));            
            
        }
    }
}
