using AutoMapper;
using MicroS_Common.Handlers;
using WeCotation.domain.Parametres.Domain;
using WeCotation.domain.Parametres.Dto;
using WeCotation.domain.Parametres.Queries;
using WeCotation.Services.Repositories;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Fri May 15 2020 14:01:25 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.Services.Cotation.Handlers
{
    /// <summary>
    /// Browse Parametre Handler
    /// </summary>
    public partial class BrowseParametreHandlerGen : BaseBrowseHandler<Parametre, BrowseParametres, ParametreDto, IBrowseParametreRepository>
    {
        public BrowseParametreHandlerGen(IBrowseParametreRepository repository, IMapper mapper) : base(repository, mapper){}
    }
}
