using MicroS_Common.Types;
using WeCotation.domain.Articles.Dto;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Wed May 13 2020 11:51:54 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.domain.Articles.Queries
{
    public class BrowseArticles : PagedQueryBase, IQuery<PagedResult<ArticleDto>>
    {
        public string Type { get; set; }
        public string Code { get; set; }
        public string Designation { get; set; }
    }
}
