#region using
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MicroS_Common.Types;
using MicroS_Common.Controllers;
using MicroS_Common.Dispatchers;
using WeCotation.domain.TypeMatieres.Dto;
using WeCotation.domain.TypeMatieres.Queries;
#endregion

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun May 10 2020 15:33:43 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.Services.TypeMatieres.Controllers
{
    [Route("typematieres")]
    public partial class TypeMatieresController : BaseController
    {
        public TypeMatieresController(IDispatcher dispatcher) : base(dispatcher)
        {
        }

        [HttpGet("")]
        public async Task<ActionResult<PagedResult<TypeMatiereDto>>> Get([FromQuery] BrowseTypeMatieres query)
            => Collection(await QueryAsync(query));

        [HttpGet("{id}")]
        public async Task<ActionResult<TypeMatiereDto>> Get([FromRoute] GetTypeMatiere query)
            => Single(await QueryAsync(query));
        
        
    }
}