using System;
using System.Collections.Generic;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Wed May 13 2020 12:00:12 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.domain.Nomenclatures.Dto
{
    public partial class NomenclatureDto
    {

        #region private variables
        
        #endregion

        #region public properties
        
        
        public Guid Code  {get;set;}
        
        public int Operation  {get;set;}
        
        public float Quantite  {get;set;}
        
        
        #endregion


    }
}
