using AutoMapper;
using MicroS_Common.Handlers;
using WeCotation.domain.TypeMatieres.Domain;
using WeCotation.domain.TypeMatieres.Dto;
using WeCotation.domain.TypeMatieres.Queries;
using WeCotation.Services.Repositories;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun May 10 2020 15:33:43 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.Services.Cotation.Handlers
{
    /// <summary>
    /// Browse TypeMatiere Handler
    /// </summary>
    public partial class BrowseTypeMatiereHandlerGen : BaseBrowseHandler<TypeMatiere, BrowseTypeMatieres, TypeMatiereDto, IBrowseTypeMatiereRepository>
    {
        public BrowseTypeMatiereHandlerGen(IBrowseTypeMatiereRepository repository, IMapper mapper) : base(repository, mapper){}
    }
}
