using AutoMapper;
using MicroS_Common.Handlers;
using MicroS_Common.RabbitMq;
using MicroS_Common.Types;
using MicroS_Common.Mongo;
using System.Threading.Tasks;
using WeCotation.domain.TypeMatieres.Domain;
using WeCotation.domain.TypeMatieres.Messages.Commands;
using WeCotation.domain.TypeMatieres.Messages.Events;
using WeCotation.Services.Repositories;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun May 10 2020 15:33:43 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.Services.TypeMatieres.Handlers
{
    /// <summary>
    /// Delete TypeMatiere Handler
    /// </summary>
    public partial class CreateTypeMatiereHandler : DomainCommandHandler<CreateTypeMatiere,TypeMatiere>
    {
        

        #region Constructors
        public CreateTypeMatiereHandler(
            IBrowseTypeMatiereRepository repository,
            IBusPublisher busPublisher,
            IMapper mapper):base(busPublisher,mapper,repository){}
        #endregion

        #region Protected Overrides functions
        /// <summary>
        /// Check if the model exist by Command
        /// </summary>
        /// <param name="command">The command in wich information can be use do check if the model exist in database</param>
        /// <returns>Nothing</returns>
        protected override async Task CheckExist(TypeMatiere domain)
        {
            if (await Repository.ExistsAsync(domain.Id))
            {
                throw new MicroSException("typematiere_already_exists",$"TypeMatiere: '{domain.Id}' already exists.");
            }
           
        }
        #endregion

        #region Public Overrides functions
        /// <summary>
        ///  Handle the command with context
        /// </summary>
        /// <param name="command">The command to handle</param>
        /// <param name="context">The correlation context</param>
        /// <returns></returns>
        public override async Task HandleAsync(CreateTypeMatiere command, ICorrelationContext context)
        {

            await base.HandleAsync(command, context);

            var product = GetDomainObject(command);
            
            await Repository.AddAsync(product);

            await BusPublisher.PublishAsync(CreateEvent<TypeMatiereCreated>(command), context);
        }
        #endregion
    }
}
