using System;
using System.Collections.Generic;
/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun May 10 2020 17:30:35 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.domain.Matieres.Dto
{
    public class MatiereDto
    {

        #region private variables
        
        #endregion

        #region public properties
        
        
        public string Designation  {get;set;}
        
        public float PrixKg  {get;set;}
        
        
        #endregion


    }
}
