using System;
using System.Collections.Generic;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Fri May 15 2020 14:01:25 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.domain.Parametres.Dto
{
    public partial class ParametreDto
    {

        #region private variables
        
        #endregion

        #region public properties
        
         public Guid Id { get; set; }
        
        
        public string Code  {get;set;}
        
        public string Nom  {get;set;}
        
        public string Type  {get;set;}
        
        public string Aide  {get;set;}
        
        
        #endregion


    }
}
