using System;

using System.Collections.Generic;
using WeCotation.domain.Tarifs.Domain;
using WeCotation.domain.Nomenclatures.Domain;
using WeCotation.domain.Operations.Domain;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Wed May 13 2020 11:51:54 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.domain.Articles.Messages.Commands
{

    public class CreateArticle : ArticleBaseCommand
    {

        public override Guid Id { get; set; }

        public string Code { get; }
        public string Designation { get; }
        public string Indice { get; }
        public string Plan { get; }
        public float Prix { get; }
        public float Densite { get; }
        public int TxPrep { get; }
        public float TxOpe { get; }
        public float TpPrep { get; }
        public float TpOpe { get; }
        public float TpBase { get; }
        public string Type { get; }
        public List<Tarif> Tarifs { get; }
        public List<Nomenclature> Nomenclatures { get; }
        public List<Operation> Operations { get; }



        public CreateArticle(
            Guid id, string code, string designation, string indice, string plan, float prix, float densite, int txprep, float txope, float tpprep, float tpope, float tpbase, string type, List<Tarif> tarifs, List<Nomenclature> nomenclatures, List<Operation> operations) : base()
        {

            Id = id;

            Code = code;
            Designation = designation;
            Indice = indice;
            Plan = plan;
            Prix = prix;
            Densite = densite;
            TxPrep = txprep;
            TxOpe = txope;
            TpPrep = tpprep;
            TpOpe = tpope;
            TpBase = tpbase;
            Type = type;
            Tarifs = tarifs;
            Nomenclatures = nomenclatures;
            Operations = operations;

        }
    }
}
