using AutoMapper;
using WeCotation.domain.Tarifs.Domain;
using WeCotation.domain.Tarifs.Dto;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Wed May 13 2020 11:58:04 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.domain.Tarifs.Mapping
{
    public class TarifProfile:Profile
    {
        public TarifProfile()
        {
            this.AllowNullCollections = false;
            this.AllowNullDestinationValues = false;
            CreateMap<Tarif, TarifDto>();//.ConstructUsing(e => new TarifDto() {Quantite = e.Quantite,PrixBrut = e.PrixBrut,Coef = e.Coef,Commentaire = e.Commentaire  });
            
        }
    }
}
