using System;

using MicroS_Common.Mongo;



using MicroS_Common.Types;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Fri May 15 2020 14:01:24 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.domain.Parametres.Domain
{
    [MongoDocument("parametre")]
    public partial class Parametre  :BaseEntity
    {
        #region private variables
        
        #endregion


        #region public properties
       
        public string Code {get;set;}
public string Nom {get;set;}
public string Type {get;set;}
public string Aide {get;set;}


        #endregion

        #region Constructeur
        public Parametre():base(){}
        
        public Parametre(string code,string nom,string type,string aide)
            : base()
        {
            Code =code; 
Nom =nom; 
Type =type; 
Aide =aide; 
        }
        
        #endregion
        #region public functions
        #endregion

    }
}
