using MongoDB.Bson.Serialization.Attributes;
using System;




/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Wed May 13 2020 12:00:12 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.domain.Nomenclatures.Domain
{

    public partial class Nomenclature
    {
        #region private variables

        #endregion


        #region public properties

        [BsonElement("code")]
        public Guid Code { get; set; }
        [BsonElement("operation")]
        public int Operation { get; set; }
        [BsonElement("quantite")]
        public float Quantite { get; set; }


        #endregion

        #region Constructeur
        public Nomenclature() : base() { }

        public Nomenclature(Guid code, int operation, float quantite)
        : base()
        {
            Code = code;
            Operation = operation;
            Quantite = quantite;
        }

        #endregion
        #region public functions
        #endregion

    }
}
