using AutoMapper;
using MicroS_Common.Handlers;
using MicroS_Common.Types;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Threading.Tasks;
using WeCotation.domain.Articles.Domain;
using WeCotation.domain.Articles.Dto;
using WeCotation.domain.Articles.Queries;
using WeCotation.Services.Repositories;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Wed May 13 2020 11:51:54 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.Services.Cotation.Handlers
{
    /// <summary>
    /// Browse Article Handler
    /// </summary>
    public partial class BrowseArticleHandlerGen : BaseBrowseHandler<Article, BrowseArticles, ArticleDto, IBrowseArticleRepository>
    {
        public BrowseArticleHandlerGen(IBrowseArticleRepository repository, IMapper mapper) : base(repository, mapper)
        {


        }
        

    }
}
