using AutoMapper;
using MicroS_Common.Handlers;
using MicroS_Common.RabbitMq;
using MicroS_Common.Types;
using MicroS_Common.Mongo;
using System.Threading.Tasks;
using WeCotation.domain.Articles.Domain;
using WeCotation.domain.Articles.Messages.Commands;
using WeCotation.domain.Articles.Messages.Events;
using WeCotation.Services.Repositories;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Wed May 13 2020 11:51:54 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.Services.Articles.Handlers
{


    /// <summary>
    /// Delete Article Handler
    /// </summary>
    public partial class DeleteArticleHandler : DomainCommandHandler<DeleteArticle, Article>
    {
        #region Constructors
        public DeleteArticleHandler(
            IBusPublisher busPublisher, 
            IMapper mapper, 
            IBrowseArticleRepository repository) : base(busPublisher, mapper, repository)
        {
        }
        #endregion
        #region Protected Overrides functions
        /// <summary>
        /// Check if the model exist by Command
        /// </summary>
        /// <param name="command">The command in wich information can be use do check if the model exist in database</param>
        /// <returns>Nothing</returns>
        protected override async Task CheckExist(Article domain)
        {
            if (!await Repository.ExistsAsync(domain.Id))
            {
                throw new MicroSException("article_not_found",$"Article: '{domain.Id}'  was not found.");
            }

        }
        #endregion

        #region Public Overrides functions
        /// <summary>
        ///  Handle the command with context
        /// </summary>
        /// <param name="command">The command to handle</param>
        /// <param name="context">The correlation context</param>
        /// <returns></returns>
        public override async Task HandleAsync(DeleteArticle command, ICorrelationContext context)
        {
            await base.HandleAsync(command, context);
            await Repository.DeleteAsync(command.Id);
            await BusPublisher.PublishAsync(CreateEvent<ArticleDeleted>(command) , context);

        }
        #endregion
    }
}
