using AutoMapper;
using MicroS_Common.Handlers;
using MicroS_Common.Mongo;
using System.Threading.Tasks;
using WeCotation.domain.Articles.Dto;
using WeCotation.domain.Articles.Queries;
using WeCotation.Services.Repositories;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Wed May 13 2020 11:51:54 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.Services.Articles.Handlers
{
    /// <summary>
    /// Get Article Handler
    /// </summary>
    public partial class GetArticleHandler :  IQueryHandler<GetArticle, ArticleDto>
    {
        

        #region Constructors
        public GetArticleHandler(
            IBrowseArticleRepository repository,
             IMapper mapper)
        {
            Repository = repository;
            Mapper = mapper;
        }
        #endregion

        #region public properties
        public IBrowseArticleRepository Repository{get;}
        public IMapper Mapper{get;}
        #endregion

        #region public functions
        /// <summary>
        ///  Handle the command with context
        /// </summary>
        /// <param name="command">The command to handle</param>
        /// <param name="context">The correlation context</param>
        /// <returns></returns>
        public async Task<ArticleDto> HandleAsync(GetArticle query)
        {
            var model = await Repository.GetAsync(query.Id);

            return model == null ? null : Mapper.Map<ArticleDto>(model);

        }
        #endregion
    }
}