using AutoMapper;
using MicroS_Common.Handlers;
using MicroS_Common.RabbitMq;
using MicroS_Common.Repository;
using MicroS_Common.Types;
using System.Threading.Tasks;
using WeCotation.domain.Articles.Domain;
using WeCotation.domain.Articles.Messages.Commands;
using WeCotation.domain.Articles.Messages.Events;
using WeCotation.Services.Repositories;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Wed May 13 2020 11:51:54 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.Services.Articles.Handlers
{
    /// <summary>
    /// Update Article Handler
    /// </summary>
    public partial class UpdateArticleHandler : DomainCommandHandler<UpdateArticle, Article>
    {
        #region Constructors
        public UpdateArticleHandler(
            IBusPublisher busPublisher, 
            IMapper mapper, 
            IBrowseArticleRepository repo) : base(busPublisher, mapper, repo)
        {
        }
        #endregion
        #region Protected Overrides functions
        /// <summary>
        /// Check if the model exist by Command
        /// </summary>
        /// <param name="command">The command in wich information can be use do check if the model exist in database</param>
        /// <returns>Nothing</returns>
        protected override async Task CheckExist(Article domain)
        {
            if (!await Repository.ExistsAsync(domain.Id))
            {
                throw new MicroSException("product_not_found",$"Article with id: '{domain.Id}' was not found.");
            }
        }
        #endregion
        #region Public Overrides functions
        /// <summary>
        ///  Handle the command with context
        /// </summary>
        /// <param name="command">The command to handle</param>
        /// <param name="context">The correlation context</param>
        /// <returns></returns>
        public override async Task HandleAsync(UpdateArticle command, ICorrelationContext context)
        {
            
            await base.HandleAsync(command, context);
            var product = GetDomainObject(command);
            await Repository.UpdateAsync(product);
            await BusPublisher.PublishAsync(CreateEvent<ArticleUpdated>(command), context);
        }
        #endregion
    }
}
