
#region using
using AutoMapper;
using MicroS_Common.Mongo;
using MicroS_Common.Repository;
using WeCotation.domain.Articles.Domain;
using WeCotation.domain.Articles.Dto;
using WeCotation.domain.Articles.Queries;
#endregion

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Wed May 13 2020 11:51:54 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.Services.Repositories
{    

    #region interface
    /// <summary>
    /// Article Repository for intereaction with database
    /// </summary>
    public interface IBrowseArticleRepository : IBrowseRepository<Article,BrowseArticles,ArticleDto>{}
    #endregion 

    #region Implementation
    /// <summary>
    /// Article Repository for intereaction with database
    /// </summary>
    [Repository(typeof(IBrowseArticleRepository))]
    public partial class ArticleRepository : BrowseRepository<Article,BrowseArticles,ArticleDto>,IBrowseArticleRepository 
    {
        public ArticleRepository(IMongoRepository<Article> repository, IMapper mapper) : base(repository,mapper){}
        
    }
    #endregion
}