
#region using
using AutoMapper;
using MicroS_Common.Mongo;
using MicroS_Common.Repository;
using WeCotation.domain.Parametres.Domain;
using WeCotation.domain.Parametres.Dto;
using WeCotation.domain.Parametres.Queries;
#endregion

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Fri May 15 2020 14:01:25 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.Services.Repositories
{    

    #region interface
    /// <summary>
    /// Parametre Repository for intereaction with database
    /// </summary>
    public interface IBrowseParametreRepository : IBrowseRepository<Parametre,BrowseParametres,ParametreDto>{}
    #endregion 

    #region Implementation
    /// <summary>
    /// Parametre Repository for intereaction with database
    /// </summary>
    [Repository(typeof(IBrowseParametreRepository))]
    public partial class ParametreRepository : BrowseRepository<Parametre,BrowseParametres,ParametreDto>,IBrowseParametreRepository 
    {
        public ParametreRepository(IMongoRepository<Parametre> repository, IMapper mapper) : base(repository,mapper){}
        
    }
    #endregion
}