
#region using
using AutoMapper;
using MicroS_Common.Mongo;
using MicroS_Common.Repository;
using WeCotation.domain.TypeMatieres.Domain;
using WeCotation.domain.TypeMatieres.Dto;
using WeCotation.domain.TypeMatieres.Queries;
#endregion

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun May 10 2020 15:33:43 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.Services.Repositories
{    

    #region interface
    /// <summary>
    /// TypeMatiere Repository for intereaction with database
    /// </summary>
    public interface IBrowseTypeMatiereRepository : IBrowseRepository<TypeMatiere,BrowseTypeMatieres,TypeMatiereDto>{}
    #endregion 

    #region Implementation
    /// <summary>
    /// TypeMatiere Repository for intereaction with database
    /// </summary>
    [Repository(typeof(IBrowseTypeMatiereRepository))]
    public partial class TypeMatiereRepository : BrowseRepository<TypeMatiere,BrowseTypeMatieres,TypeMatiereDto>,IBrowseTypeMatiereRepository 
    {
        public TypeMatiereRepository(IMongoRepository<TypeMatiere> repository, IMapper mapper) : base(repository,mapper){}
        
    }
    #endregion
}