using AutoMapper;
using WeCotation.domain.Operations.Domain;
using WeCotation.domain.Operations.Dto;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Wed May 13 2020 12:07:33 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.domain.Operations.Mapping
{
    public class OperationProfile:Profile
    {
        public OperationProfile()
        {
            this.AllowNullCollections = false;
            this.AllowNullDestinationValues = false;
            CreateMap<Operation, OperationDto>();//.ConstructUsing(e => new OperationDto() {Code = e.Code,Ordre = e.Ordre,Nombre = e.Nombre,TxPrep = e.TxPrep,TxOpe = e.TxOpe,TpPrep = e.TpPrep,TpOpe = e.TpOpe,BaseOpe = e.BaseOpe,Commentaire = e.Commentaire  });
            
        }
    }
}
