using MicroS_Common.Types;
using System;
using WeCotation.domain.Parametres.Dto;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Fri May 15 2020 14:01:25 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.domain.Parametres.Queries
{
    public class GetParametre : IQuery<ParametreDto>
    {
        #region public properties
        
            public Guid Id { get; set; }
        
        #endregion
        
    }
}
