using MongoDB.Bson.Serialization.Attributes;
using System;




/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Wed May 13 2020 11:58:04 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.domain.Tarifs.Domain
{

    public partial class Tarif
    {
        #region private variables

        #endregion


        #region public properties

        [BsonElement("quantite")]
        public int Quantite { get; set; }
        [BsonElement("prixbrut")]
        public float PrixBrut { get; set; }
        [BsonElement("coef")]
        public float Coef { get; set; }
        [BsonElement("commentaire")]
        public string Commentaire { get; set; }


        #endregion

        #region Constructeur
        public Tarif() : base() { }

        public Tarif(int quantite, float prixbrut, float coef, string commentaire)
        : base()
        {
            Quantite = quantite;
            PrixBrut = prixbrut;
            Coef = coef;
            Commentaire = commentaire;
        }

        #endregion
        #region public functions
        #endregion

    }
}
