using System;
using System.Collections.Generic;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Wed May 13 2020 11:58:04 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeCotation.domain.Tarifs.Dto
{
    public partial class TarifDto
    {

        #region private variables
        
        #endregion

        #region public properties
        
        
        public int Quantite  {get;set;}
        
        public float PrixBrut  {get;set;}
        
        public float Coef  {get;set;}
        
        public string Commentaire  {get;set;}
        
        
        #endregion


    }
}
